### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.so.sorpc.demo.api.UserService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [100]
}



### 获取用户信息1
POST http://localhost:8080/
Content-Type: application/json

{
"service": "com.so.sorpc.demo.api.UserService",
"methodSign": "findById@1_java.lang.String",
"args": ["hello"]
}


### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.so.sorpc.demo.api.OrderService",
  "methodSign": "findById@1_java.lang.Long",
  "args": [100]
}