server:
  port: 8081
sorpc:
  zkServer: localhost:2181
  zkRoot: sorpc


app:
  id: soapp1
  env: dev
  namespace: public
  metas: "{dc: 'bj', gray: 'false', unit: 'B001'}"
  grayRatio: 33

logging:
  level:
    root: error
    com.so.sorpc: debug
