server:
  port: 8081
sorpc:
  zk:
    server: localhost:2181
    root: sorpc
  app:
    id: soapp1
    env: dev
    namespace: public
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 20
soregistry:
  servers: http://localhost:8484
logging:
  level:
    root: error
    com.so.sorpc: debug
    com.ctrip: info

app:
  id: app1
apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: app1,application
    eagerLoad:
      enabled: false
