server:
  port: 8081
sorpc:
  zk:
    server: localhost:2181
    root: sorpc
  app:
    id: soapp1
    env: dev
    namespace: public
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
logging:
  level:
    root: error
    com.so.sorpc: debug
