server:
  port: 8088
sorpc:
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zkServer: localhost:2181
  zkRoot: sorpc

app:
  id: soapp1
  env: dev
  namespace: public
  retries: 1
  timeout: 1000

logging:
  level:
    root: error
    com.so.sorpc: debug # 这个基本改成info就不会输出debug日志